name: 'Kang De Ploy'
description: 'Hit the KDP for posting thread in Slack'
inputs:
  service:
    description: 'Service name'
    required: true
    default: 'Kang De Ploy'
  tag:
    description: 'Service tag'
    required: true
    default: 'v.0.0'
  pic:
    description: 'PIC Deployment'
    required: true
    default: 'Kang De Ploy'
  rfc:
    description: 'RFC'
    required: true
    default: '-'
  content:
    description: 'content'
    required: true
    default: '-'
# outputs:
#   success: 
#     description: 'response'
runs:
  using: 'composite'
  steps:
    - run: python -m pip install PyGithub  # Installing dependencies
      shell: bash
    - run: python ${{ github.action_path }}/hit_kdp.py
      shell: bash
  # image: 'Dockerfile'
  # args:
  #   - ${{ inputs.service }}
  #   - ${{ inputs.tag }}
  #   - ${{ inputs.pic }}
  #   - ${{ inputs.content }}