name: 'Kang De Ploy'
description: 'Hit the KDP for posting thread in Slack'
inputs:
  service:
    description: 'Service name'
    required: true
    default: 'Kang De Ploy'
  host:
    description: 'KDP host'
    required: true
    default: 'localhost'

# runs:
#   using: 'composite'
#   steps:
#     - run: python -m pip install PyGithub
#       shell: bash
#     - run: python ${{ github.action_path }}/hit_kdp.py ${{ inputs.token }} ${{ inputs.org }} ${{ inputs.repo }} ${{ inputs.host }} ${{ inputs.service }}
#       shell: bash
# runs:
#   using: 'docker'
#   image: 'Dockerfile'
#   env:
#     token: ${{ inputs.token }}
#     org: ${{ inputs.org }}
#     repo: ${{ inputs.repo }}
#     host: ${{ inputs.host }}
#     service: ${{ inputs.service }}

runs:
  using: 'node16'
  main: 'main.js'